### ISSUE TITLE
NPE while running file sink connector on 0.10.0.0-cp1

### ISSUE THREAD

**Issue by 1ambda** [1ambda/kafka-connect-dashboard#11]
```
[2016-08-19 20:30:35,463] ERROR Failed to reconfigure connector's tasks, retrying after backoff: (org.apache.kafka.connect.runtime.distributed.DistributedHerder:807)
java.lang.NullPointerException
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:51)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
        at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:79)
        at org.apache.kafka.connect.runtime.SourceConnectorConfig.<init>(SourceConnectorConfig.java:29)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnector(DistributedHerder.java:845)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnectorTasksWithRetry(DistributedHerder.java:799)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$800(DistributedHerder.java:92)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$11$1.call(DistributedHerder.java:812)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$11$1.call(DistributedHerder.java:809)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:232)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:176)
        at java.lang.Thread.run(Thread.java:745)
[2016-08-19 20:30:35,463] ERROR Unexpected error during connector task reconfiguration:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:818)
[2016-08-19 20:30:35,463] ERROR Task reconfiguration for FileConnector1 failed unexpectedly, this connector will not be properly reconfigured unless manually triggered. (org.apache.kafka.connect.runtime.distributed.DistributedHerder:819)
```

**Comment by 1ambda** [comment]
It's because we **POST**ed  a connector which has no 'name' field in config
